### ISSUE TITLE
DS: Premissas

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#1]
Definição de premissas do Design System:

Conectividade baixa
Acessibilidade
Uso de frameworks / bibliotecas para dev

**Utilização dos documentos:** 
DS UNICEF - https://unicef.github.io/design-system/design-guidelines.html 
Brand Book - https://drive.google.com/file/d/1ja7Z5ceal9rUN0oYcyD8mYbpnhLclG1x/view?usp=sharing

**Comment by fialalucas** [comment]
Estou presente
