### ISSUE TITLE
UI: Painel de dados (v0)

### ISSUE THREAD

**Issue by leonardodms-unicef** [UNICEF01/Design-System#114]
» modal lista de vacinas;
» ícone "i" (mais infos)

**Comment by dlazaroni** [comment]
https://xd.adobe.com/view/c87ed8ab-fbd3-415f-8f70-95713b6bfcdf-9d2d/

**Comment by leonardodms-unicef** [comment]
![Painel – Visão Gestor Nacional.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/baf4c397-0f54-4d63-8420-d9933cdf1cbe)

**Comment by leonardodms-unicef** [comment]
![Painel – Visão Gestor Nacional - Lista de vacinas.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/638dc58d-bb93-4187-b1f8-f7cba6127deb)

**Comment by leonardodms-unicef** [comment]
Em relatório: Out/22
