### ISSUE TITLE
UI - Mapa

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#128]

**Comment by fialalucas** [comment]
Link para Dev
https://xd.adobe.com/view/b74af951-892f-4745-b3e1-ac464538c022-e219/

**Comment by lucasferreiraunicef** [comment]
Boa noite, Fiala.

Tudo bem ?

Sobre as duas tasks em review, podemos bater um papo com o Guilherme para validar os itens, digo no sentido análise técnica e viabilidade de acordo com as libs que o front está utilizando. Podemos?
________________________________
De: Lucas Fiala ***@***.***>
Enviado: terça-feira, 10 de maio de 2022 14:14
Para: UNICEF01/Design-System ***@***.***>
Cc: Lucas Ricardo Ferreira Rocha ***@***.***>; Mention ***@***.***>
Assunto: Re: [UNICEF01/Design-System] UI - Mapa (Issue #128)


Por gentileza, confirma pra mim se está validado @lucasferreiraunicef<https://github.com/lucasferreiraunicef>

**Comment by fialalucas** [comment]
Dev Link - https://xd.adobe.com/view/5e8a0641-a8f6-4c58-9da7-7383c1bba8a5-0bd9/
