### ISSUE TITLE
UI - RS3 - Mobile

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#129]

**Comment by fialalucas** [comment]
Dev Link
https://xd.adobe.com/view/3c95ad06-7ecb-4c4d-90d8-0901ffb6c3db-69c6/

**Comment by fialalucas** [comment]
Por gentileza, confirma pra mim se está validado @lucasferreiraunicef

**Comment by lucasferreiraunicef** [comment]
Fiala, aprovado. Precisamos analisar agora com algum dev do SELO.
