### ISSUE TITLE
DS: Navbar

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#13]

**Comment by fialalucas** [comment]
![image.png](https://images.zenhubusercontent.com/623a3fd7095b23600bfd79ce/b6644b3a-c1b7-4f68-b443-4ac6706e0e4e)

**Comment by fialalucas** [comment]
![image.png](https://images.zenhubusercontent.com/623a3fd7095b23600bfd79ce/d270ec5a-10ce-42b1-a775-c76752916285)

**Comment by fialalucas** [comment]
![image.png](https://images.zenhubusercontent.com/623a3fd7095b23600bfd79ce/e4252454-f1c9-4dbf-ae26-261a9d930416)
