### ISSUE TITLE
Logomarca MAAp

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#135]

**Comment by dlazaroni** [comment]
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/921d541f-4843-41b9-8616-9fc012d170b8)

**Comment by leonardodms-unicef** [comment]
![Logo.MAAp.svg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/72a23278-9ccd-4da9-bd24-58cebcd9dddc)

![Logo.MAAp-1.svg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/9ca3cbe4-f4dd-44a9-8702-55fbfea2de6b)

![Logo.MAAp-2.svg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/2a6a3613-79ad-4568-b752-9948345b7395)

![Logo.MAAp-3.svg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/f5255b6f-1167-476a-ba34-ff7374f8fe51)

**Comment by leonardodms-unicef** [comment]
Em relatório: Mai/22
