### ISSUE TITLE
UI: Programa: Cronograma - Atividade

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#137]
Indicadores e Alertas

Dependente do alinhamento entre Nikklas e equipe ABC

**Comment by leonardodms-unicef** [comment]
Em relatório: Mai/22

**Comment by leonardodms-unicef** [comment]
![137-maap-cronograma-atividade.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/2bedd653-38c6-4949-b0ec-ac28aa8dda9f)

**Comment by leonardodms-unicef** [comment]
Protótipo XD: https://xd.adobe.com/view/ea0532b2-7c74-495e-8798-9ff451dd10b5-bf56/
