### ISSUE TITLE
UX/UI: Instituições

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#138]
https://xd.adobe.com/view/986b509b-42fc-4e10-bc30-02bb03a49b41-cd38/

**Comment by leonardodms-unicef** [comment]
![138 – MAAp – Instituições - criar – com departamentos.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/9f4c238f-4cef-4739-a594-70caba34ab77)

**Comment by leonardodms-unicef** [comment]
![138 – MAAp – Instituições - lista – 1.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/16c12c0c-5f17-4055-af29-8f0be6e78930)

**Comment by leonardodms-unicef** [comment]
Em relatório: Ago/22
