### ISSUE TITLE
Ajustes UI - Alerta

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#145]
- [x] Adicionar barra de acessibilidade;

- [x] Ícone vacina no bottom e deixar ele no topo também;

- [x] Criar alerta: Motivos com encaminhamento para outra secretaria

- [x] Criar alerta: criança, adolescente e gestante

- [x] Criar alerta: "Não tem imagem da carteirinha" (listar outros motivos)

- [x] Meus alertas: ajustar filtragem (etapa atual)

**Comment by dlazaroni** [comment]
@leonardodms-unicef coloca o link?

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/33b27422-0800-4d3c-92c2-20fccc1da6a2-66e1/

**Comment by leonardodms-unicef** [comment]
Em relatório: Mai/22

**Comment by leonardodms-unicef** [comment]
![108-145-ajustes-ui-alerta.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/4fdb0bd6-e224-4047-a798-a991582efb2a)
