### ISSUE TITLE
UI: Caso

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#149]
Protótipo Design Review: https://xd.adobe.com/view/583bc08a-8fdf-4366-8525-25b196d30d4c-0d68/

**Comment by leonardodms-unicef** [comment]
![149-casos-analise.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/fd3aa276-45e1-4094-8cb7-d4a4c9270be8)

**Comment by leonardodms-unicef** [comment]
Em relatório: Mai/22
