### ISSUE TITLE
DS: Footer

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#15]

**Comment by fialalucas** [comment]
![image.png](https://images.zenhubusercontent.com/623a3fd7095b23600bfd79ce/fb092944-01fd-4731-9259-d7e8b2570514)

**Comment by fialalucas** [comment]
![image.png](https://images.zenhubusercontent.com/623a3fd7095b23600bfd79ce/6bd93387-00ec-4dea-9c73-0d1d5aefd5cd)
