### ISSUE TITLE
Busca: Todas as telas

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#170]

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/a3df1331-e23d-46ac-bd15-5f8d12eb9f95-f68c/

**Comment by leonardodms-unicef** [comment]
![170 – MAAp – Matriz Lógica - Visão única - Completa – Produto expandido.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/7f03e9c5-bb5d-4176-b8d0-5eb968cdb8e9)

**Comment by leonardodms-unicef** [comment]
![170 – MAAp – Matriz Lógica - Inserir Linha - Resultado – Indicador preenchido.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/63a29ab1-af05-413e-91d8-dfaf8a1f264d)

**Comment by leonardodms-unicef** [comment]
Em relatório: Ago/22
