### ISSUE TITLE
UI: Programa: Cronograma

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#173]

**Comment by leonardodms-unicef** [comment]
![173 - Programa Cronograma – Zoom Trimestre.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/0a1a111c-d2be-48cd-8e1a-fa46dd79dd3e)

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/44be735b-216e-477a-a03d-46b6ca069ff2-11ed/

**Comment by leonardodms-unicef** [comment]
Em relatório: Jun/22
