### ISSUE TITLE
UX/UI: Ajustes Alertas

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#175]
- [x] Incluir caso sem carteirinha;

- [x] Incluir conexão com BAE (criança fora da escola)

**Comment by leonardodms-unicef** [comment]
![175-bav-ajustes-alertas.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/d7cbd307-e92f-4372-a903-7163be1fbb27)

**Comment by leonardodms-unicef** [comment]
Em relatório
