### ISSUE TITLE
Programa: Lista de Programas cadastrados

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#186]
[10:51] Daniel Lazaroni Apolinario
    todos os programas (vazio) - retirar busca, deixar texto de introdução mais botão inserir novo programa
​[11:03] Daniel Lazaroni Apolinario
    tirar check de descrição na duplicação do programa
​[11:09] Daniel Lazaroni Apolinario
    aprovação: mostrar fotos dos perfis que aprovam e o status de cada um (quem aprovou e quem ainda não aprovou)
​[11:19] Daniel Lazaroni Apolinario
    indicar matriz ativa e desativada no submenu
​[11:20] Daniel Lazaroni Apolinario
    adicionar ícone de ativa/desativada na edição/criação da matriz (ao lado do título). Obs: Ver página de criação de indicador

**Comment by dlazaroni** [comment]
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/abd4eba5-f572-4574-8375-7c780472a5e6)

**Comment by leonardodms-unicef** [comment]
![186 - Programa - Uma aberta – 1.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/f675ef4a-ded4-4964-9a1d-e61a6b042658)

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/4a55ae4e-2fa2-4f16-9aaa-1281853b91fd-1f06/

**Comment by leonardodms-unicef** [comment]
Em relatório: Jun/22
