### ISSUE TITLE
Programa: Monitoramento - UI Ajustes

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#187]
- trocar plano de fundo;
- espaçamento...

**Comment by leonardodms-unicef** [comment]
![187 - Programa - Monitoramento.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/2e539d44-7916-4efd-b4ff-181a2be5a319)

**Comment by leonardodms-unicef** [comment]
![187 - Programa - Monitoramento - Editar – 2.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/9bb12b64-39e5-490d-a034-242124ee868b)

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/6f952c95-68eb-4da2-9bfc-f87622fc6f9a-3ac6/

**Comment by leonardodms-unicef** [comment]
Em relatório: Jun/22
