### ISSUE TITLE
UI Mobile: Participação Cidadã

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#191]

**Comment by fialalucas** [comment]
Dev Link - https://xd.adobe.com/view/1b130628-74a2-492f-8407-2f0629cb5e64-4e40/

**Comment by fialalucas** [comment]
Segue link conforme combinado @lucasferreiraunicef

**Comment by lucasferreiraunicef** [comment]
Obrigado Fiala.

Att,


Lucas Ferreira
Scrum Master

UNICEF Brazil

E-mail: ***@***.******@***.***>



United Nations Children's Fund

SEPN 510, Bloco A, 2º andar, Brasília, DF, Brazil
Follow us on Facebook<http://www.facebook.com/UNICEFBrasil>, Twitter<http://www.twitter.com/unicefbrasil>, Instagram<http://www.instagram.com/unicefbrasil>, YouTube<http://www.youtube.com/unicefbrasil> and at www.unicef.org.br<http://www.unicef.org.br/>

________________________________
De: Lucas Fiala ***@***.***>
Enviado: sexta-feira, 15 de julho de 2022 15:37
Para: UNICEF01/Design-System ***@***.***>
Cc: Lucas Ricardo Ferreira Rocha ***@***.***>; Mention ***@***.***>
Assunto: Re: [UNICEF01/Design-System] UI Mobile: Participação Cidadã (Issue #191)


Segue link conforme combinado @lucasferreiraunicef<https://github.com/lucasferreiraunicef>
