### ISSUE TITLE
DS: Levantamento e definição de frameworks

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#2]
Estudo e levantamentos de frameworks a serem utilizados (em **negrito** os escolhidos):

» Bootstrap;
» Bulma;
» Tailwind;
**» Material Design + Vuetify (sugerido pelos devs)**

Para gráficos:
» Chats JS
» Apexchart JS
**» FisionCharts** (sugerido pelo Barboni / já utilizado na BAE)

Ícones:
» Font Awesome;
**» MAterial Design Symbols**

Em negrito os frameworks escolhidos.

PS: falta validação com devs

**Comment by fialalucas** [comment]
No final do dia 23 tivemos um feedback onde foi proposto alteração de framework para o Vuetify (compartilhei com vocês no XD ) e o FisionCharts (este que já vem sido utilizado na BAE). Ainda ficaram de nos enviar um email com maiores detalhes.
