### ISSUE TITLE
Programa: Matriz Lógica - Ajustes 2

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#207]
- Dupla validação: Implementar: os usuários responsáveis pela Matriz Lógica devem aprovar a ML para a mesma ficar ativa Somente poderá ser editada a matriz lógica após a aprovação, com revisão e aprovação dos usuários responsáveis

- Indicar somente uma matriz ativa

- Criar Matriz: Adicionar parceiros responsáveis + usuários responsáveis

**Comment by leonardodms-unicef** [comment]
![207 - Matriz Lógica - Visão única - Com Produtos.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/99feffa3-b1c1-436a-8e94-846ed9151d99)

**Comment by leonardodms-unicef** [comment]
[Uploading... 207 - Matriz Lógica - Inserir Linha - Resultado – Inserir Premissas – 3.png]

**Comment by leonardodms-unicef** [comment]
[Uploading... 207 - Matriz Lógica - Todas - Fechada – 4.png]

**Comment by leonardodms-unicef** [comment]
![207 - Matriz Lógica - Inserir Linha - Resultado – Inserir Premissas – 3.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/fbad9d61-342b-4dbe-b4c4-be333fd790cf)

**Comment by leonardodms-unicef** [comment]
[Uploading... 207 - Matriz Lógica - Todas - Fechada – 4.png]

**Comment by leonardodms-unicef** [comment]
[Uploading... 207 - Matriz Lógica - Todas - Fechada – 4.png]

**Comment by leonardodms-unicef** [comment]
![207 - Matriz Lógica - Todas - Fechada – 4.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/bb451795-d774-4f0f-8d96-2fdcb4cc8e7a)

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/0569ac7c-d1a1-4cdc-b93e-566bcbd7ccdb-503a/

**Comment by leonardodms-unicef** [comment]
Em relatório: Jun/22
