### ISSUE TITLE
Programa: Cronograma + Plano de trabalho - dupla validação

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#208]
https://xd.adobe.com/view/44be735b-216e-477a-a03d-46b6ca069ff2-11ed/

**Comment by leonardodms-unicef** [comment]
![208 - Matriz Lógica - Cronograma - concluir – Dupla Validação.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/99482c94-4e3e-44d3-ab6e-37382798a4f2)

**Comment by leonardodms-unicef** [comment]
Em relatório: Jul/22
