### ISSUE TITLE
Programa: navbar - ajustes

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#209]
"Plano de TRabalho, Cronograma..... Arquivos" estão dentro de uma matriz lógica criada.
item "Matriz Lógica" da navbar não faz sentido estar no mesmo nível que os demais itens

**Comment by leonardodms-unicef** [comment]
![209 - Web 1920 – fechada.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/9c81f05b-66d6-4459-9516-9019bada59b1)

**Comment by leonardodms-unicef** [comment]
[Uploading... 209 - Web 1920 – Menu.png]

**Comment by leonardodms-unicef** [comment]
[Uploading... 209 - Web 1920 – Menu Pessoal.png]

**Comment by leonardodms-unicef** [comment]
Em relatório: Jun/22

**Comment by leonardodms-unicef** [comment]
![209 - Web 1920 – Menu.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/852afd72-d887-4de4-82e2-366e14fe8a1c)

**Comment by leonardodms-unicef** [comment]
![209 - Web 1920 – Menu Pessoal.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/5fedab5e-742b-4d02-91f8-3ab43ea5fe21)

**Comment by leonardodms-unicef** [comment]
Em relatório: Jun/22
