### ISSUE TITLE
Ajustes UI/UX Caso (Análise Técnica)

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#227]
- Colocar data de aplicação para as vacinas tomadas e que possuem mais de uma dose;

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/e1e36c79-aa81-4deb-ae85-d98e3faca238-b4b0/

**Comment by leonardodms-unicef** [comment]
![227 – BAV – Caso Etapa Análise técnica tela data de aplicação das doses – 1.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/59991068-d8ca-40c3-867c-628798e189bb)

**Comment by leonardodms-unicef** [comment]
Em relatório: Ago/22
