### ISSUE TITLE
Mobile: Caso

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#229]

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/5e7f407b-54ae-492b-b868-0fed28b51943-0b2c/

**Comment by leonardodms-unicef** [comment]
![229 – BAV – Alerta Passo 1 - Identificar – Criança - Situação do Alerta – Visita – 4.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/410b936b-bad9-4faf-8acb-be659859f39e)

**Comment by leonardodms-unicef** [comment]
Em relatório: Ago/22
