### ISSUE TITLE
Mobile: Lista Casos

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#230]

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/5e7f407b-54ae-492b-b868-0fed28b51943-0b2c/

**Comment by leonardodms-unicef** [comment]
![229 – BAV – Lista Alertas - Filtro Pendentes.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/9cdf7201-4b96-4368-b2eb-f42e787f6df0)

**Comment by leonardodms-unicef** [comment]
Em relatório: Ago/22
