### ISSUE TITLE
UI: Registro de visitas do Agente de Alerta

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#232]

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/33b27422-0800-4d3c-92c2-20fccc1da6a2-66e1/

**Comment by leonardodms-unicef** [comment]
![232 – BAV – Alerta Passo 1 - Criança – Preenchido.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/c58a72d8-4ab0-40b7-bbfe-456bc3f42edb)
