### ISSUE TITLE
loading + erro

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#241]

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/21bb3285-9c34-49dd-bafd-fa8be9852fe5-74e8/

**Comment by leonardodms-unicef** [comment]
![241-Erro Genérico Desktop.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/b6c48cdb-2144-4057-97a6-cef563f9a2d6)

**Comment by leonardodms-unicef** [comment]
![241-Loading Desktop.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/bd1f989d-058c-4b0a-a431-cc8c13509b4c)

**Comment by leonardodms-unicef** [comment]
Animação da tela "Carregando" (GIF+JS): https://unicef-my.sharepoint.com/:f:/g/personal/lesoares_unicef_org/Ejshc5NAVlpJkUwHwnjmvB0Bps7cAdOPta1nmVtPcDDm8w?e=zQjFge

**Comment by leonardodms-unicef** [comment]
Em relatório: Junho 2022

**Comment by leonardodms-unicef** [comment]
![241 - Loading BAV.gif](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/159b7e98-8989-436a-8896-187843f18cc8)
