### ISSUE TITLE
loading + erro

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#242]
- [x] Loading

- [x] Erro

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/4ddc50c6-94ae-4d2f-9e52-388f233f69d4-188f/

**Comment by leonardodms-unicef** [comment]
![242 - Erro 404 Desktop.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/edcd8338-8d27-4d2d-9ff7-931005c409f9)

**Comment by leonardodms-unicef** [comment]
![242-Loading Desktop.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/24391f6a-82da-4bfd-9289-bac99db58b6a)

**Comment by leonardodms-unicef** [comment]
Animação da tela "Carregando" (GIF+JS): https://unicef-my.sharepoint.com/:f:/g/personal/lesoares_unicef_org/EnjGsXoQptpEuhUdSLRZiBMBsK2kPfpugYyyNLpa5D801Q?e=YvNSHk

**Comment by leonardodms-unicef** [comment]
Em relatório: Junho 2022

**Comment by leonardodms-unicef** [comment]
![241 - Loading MAAp.gif](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/8c32f25e-167c-4f85-9c5a-f46a59aa6a07)
