### ISSUE TITLE
Ajustes Casos -  histórico de visitas 

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#253]
Incluir histórico de visitas nas etapas

https://xd.adobe.com/view/e1e36c79-aa81-4deb-ae85-d98e3faca238-b4b0/

**Comment by leonardodms-unicef** [comment]
![253 - BAV - Caso Etapa Visita em dia – Agente de alerta.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/00df141d-a16e-427f-8e2b-1cda4e0ff87b)

**Comment by leonardodms-unicef** [comment]
Em relatório: Jul/22
