### ISSUE TITLE
Mobile: Navbar

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#256]

**Comment by leonardodms-unicef** [comment]
![256 – BAV – Alerta Passo 1 - Identificar.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/456d3ed7-9409-4274-a042-3a859f4ca49f)

**Comment by leonardodms-unicef** [comment]
![256 – BAV – maap-mobile-menu.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/a977fd96-adad-4d12-8024-f6e0a5a69766)

**Comment by leonardodms-unicef** [comment]
Em relatório: Ago/22
