### ISSUE TITLE
Estrutura de dados / relacionamentos - Parte 2

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#257]
https://miro.com/app/board/uXjVOEyNfBY=/

**Comment by leonardodms-unicef** [comment]
![257 - MAAp - Estrutura de Dados.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/f03648a1-6a09-427c-99d5-48ba141ad335)

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
