### ISSUE TITLE
Programa: Classificações

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#261]

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/d38e6936-e343-4b9b-99f2-ac9de1c3c18c-86dd/

**Comment by leonardodms-unicef** [comment]
![261 - Classificações - Adicionar - Vazio.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/6683f261-8dba-45c6-acb4-0a82f75c4e33)

**Comment by leonardodms-unicef** [comment]
![261 - Classificações - Lista - Vários itens.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/90c5f38f-317b-4717-9d8e-c3527218ded7)

**Comment by leonardodms-unicef** [comment]
Em relatório: Jul/22
