### ISSUE TITLE
Fluxo de Notificações

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#264]
https://unicef-my.sharepoint.com/:x:/g/personal/dlazaroni_unicef_org/ES68T9cCyIxHhcgzK-Rgf2IB4rVGoAzSyN9B6pF9SXQWNw?e=lHW5ZW

**Comment by dlazaroni** [comment]
@Clivisonc pode dar uma olhada nessa documentação e complementá-la / editá-la, por favor?

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
