### ISSUE TITLE
UI: Notificações

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#265]

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/d2c979b4-f283-4062-8270-e60c888653a7-879a/

**Comment by leonardodms-unicef** [comment]
![265 – BAV – 01 – Página exemplo.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/7207091c-87cf-4dd3-a8e4-5d126ca93d60)

**Comment by leonardodms-unicef** [comment]
![265 – BAV – 01 – Notificações.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/57a31a8c-32c1-4ebb-93aa-8170d3f7b1e6)

**Comment by leonardodms-unicef** [comment]
Em relatório: Ago/22
