### ISSUE TITLE
Menu: revisar

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#268]
- adicionar Usuários;
- definir nomenclatura para Visitas/Alertas / Casos no menu

**Comment by leonardodms-unicef** [comment]
![256 – BAV – Menu.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/f5523fda-b709-4d37-9211-652bbe8e3f33)

**Comment by leonardodms-unicef** [comment]
Em relatório: Agosto/22
