### ISSUE TITLE
Fluxo diferentes perfis

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#269]
https://xd.adobe.com/view/e1e36c79-aa81-4deb-ae85-d98e3faca238-b4b0/- Lista de alertas pendentes e casos

**Comment by leonardodms-unicef** [comment]
![269 - BAV - Alerta Passo 1 - Criança – Preenchido.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/217a126a-d48a-4f4b-9e7f-67789458444d)

**Comment by leonardodms-unicef** [comment]
Em relatório: Jul/22
