### ISSUE TITLE
Matriz lógica: ajuste coluna

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#281]
"Orçamento planejado" e "Coleta final" viram:
"Contrapartida não financeira" e "Contrapartida financeira" (últimas colunas)

» Trocar ordem na tela de PRODUTO

**Comment by leonardodms-unicef** [comment]
![281 – MAAp – Matriz Lógica - Visão única - Com Produtos.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/7bc7a3b8-44e3-41a5-9800-2b90613369e5)

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/6ea356df-f452-4ff7-b64a-13446059146c-3bf0/

**Comment by leonardodms-unicef** [comment]
Em relatório: Agosto/22
