### ISSUE TITLE
Projeto: Cronograma e Plano de Trabalho

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#286]
Fundir Cronograma com Plano de Trabalho.
- Adicionar Atividade / Tarefa;
- Visualização por Gantt ou Lista (adicionar "categoria" e "produto" a uma coluna da lista);
- Filtrar por "Categoria" (já trazer as categorias finais);
- Alterar menu

**Comment by leonardodms-unicef** [comment]
![286 - MAAp - Programa Cronograma – versão Projeto.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/f1f8719f-1954-412c-b74b-30a161923652)

**Comment by leonardodms-unicef** [comment]
![286 - MAAp - Programa Cronograma – versão Projeto.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/a96f9368-0a90-4ef6-bfa8-e473766003be)

https://xd.adobe.com/view/44be735b-216e-477a-a03d-46b6ca069ff2-11ed/screen/1fd2e88b-f15d-4a2a-9a2e-4e009d818b41/

**Comment by leonardodms-unicef** [comment]
![286 - MAAp - Plano de Trabalho - Nível atividades – 1.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/2f45c9f1-48b8-4e15-952b-b4630869dbcf)

https://xd.adobe.com/view/6e8ab3bb-9459-4092-9ce1-81152284c17f-3bd9/screen/f628e22f-6f43-4fc9-8c72-ac76ee88b8af/

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
