### ISSUE TITLE
Projeto: Indicadores

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#287]
https://xd.adobe.com/view/5bc066b3-ae2b-40b6-a5da-c55e8cdc4100-0e93/

**Comment by leonardodms-unicef** [comment]
![287 - MAAp - Lista de Indicadores – De um projeto– 1.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/965ac551-95c6-4381-827a-43f421a3008a)

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
