### ISSUE TITLE
UI: Indicadores (Projeto e Programa)

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#288]
https://xd.adobe.com/view/5bc066b3-ae2b-40b6-a5da-c55e8cdc4100-0e93/

**Comment by leonardodms-unicef** [comment]
![288 - MAAp - 01 - Lista de Indicadores – 2.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/48024f39-69d7-4613-8259-28087155f2e7)

**Comment by leonardodms-unicef** [comment]
![288 - MAAp - 02 - Lista de Indicadores – De um programa.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/3870dcb5-8f64-479c-9011-b1a1f4bfd7a6)
