### ISSUE TITLE
Programa: ajustes

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#292]
- adicionar tipo de instrumento
- alterar listagem de programas

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/7fe4c579-972a-4411-8608-1893a168b8dc-2ab7/

**Comment by leonardodms-unicef** [comment]
![292 - Programas - Um item.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/9f254c88-5311-420f-ab2f-e86cddcef5c4)

**Comment by leonardodms-unicef** [comment]
Em relatório: Agosto/22
