### ISSUE TITLE
Cadastro Usuários: Indicar Regras SELO

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#295]
Trazer as "notificações pendentes" de cadastro de usuários para a lista de usuários
- 1 gestor político
- 1 coordenador operacional
- 1 supervisor institucional de cada área (Saúde (padrão) / Educação / Assistência social)
- Pelo menos 1 técnico verificador
- Pelo menos 1 agente de alerta

**Comment by leonardodms-unicef** [comment]
![295 - BAV.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/a7dfd921-a809-4944-a254-90843ba7fa0b)

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/3e18ee4e-6f29-45de-a2ee-ce753f04b88a-6b4b/

**Comment by leonardodms-unicef** [comment]
Em relatório: Agosto/22
