### ISSUE TITLE
Alinhamento Design

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#297]
- Telas com o conteúdo pré-definido

**Comment by dlazaroni** [comment]
[https://app.zenhub.com/files/472490027/a7d5874e-f947-40b9-b8b8-b77832e0bf08/download](https://app.zenhub.com/files/472490027/a7d5874e-f947-40b9-b8b8-b77832e0bf08/download)

**Comment by leonardodms-unicef** [comment]
Em relatório: set/22
