### ISSUE TITLE
Projeto: Ajustes criação/edição

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#298]
https://xd.adobe.com/view/54c6f9ee-81a5-4d81-862a-80dc607812ac-0195/

- Adicionar igualdade de gênero 
- Status/fases (e-mail);
- Fluxo de encerramento

![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/6a56482c-37dd-4b4d-a8b7-3c65a4925e89)

**Comment by leonardodms-unicef** [comment]
![298 - MAAp - Projetos - Editar com extensão.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/ea6f82fe-eb3e-40f8-9e69-b680cbbbd3f3)

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
