### ISSUE TITLE
Projeto: Matriz lógica - Pente fino UI

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#299]
Adaptações da Matriz para PROJETO: https://xd.adobe.com/view/c6c20f80-a0d2-4ee5-9d6c-1dcf0cc8486d-9391/

**Comment by dlazaroni** [comment]
@leonardodms-unicef Coloca, por favor, o link do XD Desktop_V0 (Matriz lógica de PROGRAMA)

https://xd.adobe.com/view/6ea356df-f452-4ff7-b64a-13446059146c-3bf0/

**Comment by leonardodms-unicef** [comment]
![299 - MAAp - Matriz Lógica - Visão única - Completa.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/c6f88b43-1de5-48b6-bf08-6403700af7a8)

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
