### ISSUE TITLE
UI: Adesão BAV

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#301]

**Comment by dlazaroni** [comment]
@Clivisonc Cara, ta fechado as telas de adesão

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/f999effb-fe3d-4c9a-ac5e-e22fd814fb28-acca/

**Comment by leonardodms-unicef** [comment]
![301 - BAV - Adesão - Lista de municípios.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/81314eda-7e56-461b-bc60-a870820574e6)

![301 - BAV - Adesão – Ainda não aderiu - Prefeito.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/b09fbf33-a960-4d4c-a081-6a3fa569aa8e)

**Comment by leonardodms-unicef** [comment]
![301 - BAV - Adesão - Painel – Usuários Município – 2.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/fa081941-5bb6-4dc0-8c0a-d611a648d9c7)

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
