### ISSUE TITLE
Contribuições financeiras + Orçamentos (Planejado + Executado)

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#303]
- Adicionar total no final da coluna "Alocação de proposta" (Plano de Trabalho);
- Valor Auferido;
- Planejado x Executado;
- Valores nas criações de programas e projetos;
- Conexão de valor do projeto no programa;
- Saldos do níveis superior até o inferior;

**Comment by leonardodms-unicef** [comment]
[Uploading... 303 - MAAp - Orçamento - Matriz Lógica - Visão única – Introdução.png]

**Comment by leonardodms-unicef** [comment]
![303 - MAAp - Orçamento - Matriz Lógica - Visão única – Introdução.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/cea05b3b-4a8c-4c3b-88f6-9756f9aedaff)

**Comment by leonardodms-unicef** [comment]
[Uploading... 303 - MAAp - Orçamento - Monitoramento - Subir Arquivos.png]

**Comment by leonardodms-unicef** [comment]
![303 - MAAp - Orçamento - Monitoramento - Subir Arquivos.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/c3771a12-344e-41fa-bea6-ed9525abb231)

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
