### ISSUE TITLE
Estudo geração de relatório MAAp (docx)

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#307]
Formulário de solicitação de Cooperação -  ​docx icon I3.1_1 Formulário de Solicitação de Cooperação.docx - https://unicef-my.sharepoint.com/:w:/g/personal/lviegas_unicef_org/ERU6SjG9T3FNsdW6HNQ32AABtq9mK2OJmMAlr7p7qPK6_g?e=nyLoDo

 

Termo de Referência da Missao de Prospecção - ​docx icon Termo_de_Referencia_(TR)_da_Missao_de_Prospeccao.docx - https://unicef-my.sharepoint.com/:w:/g/personal/lviegas_unicef_org/EdSC5lWiQ_FJgZmeqCEb2uMBROh58kkt2aKyJvgONBkSwQ?e=bi3RSP

 

Relatório Padrão da Missão de Prospecção - ​docx icon Relatório Padrão da Missão de Prospecção.docx - https://unicef-my.sharepoint.com/:w:/g/personal/lviegas_unicef_org/Ed6URQ8_Lb1GmU9NNwaURiEBSOXs5McGGEIZVLKbILBfqA?e=BJz5ue

 

Documento do Projeto de CSST - ​docx icon Documento_do_Projeto_de_CSST.docx - https://unicef-my.sharepoint.com/:w:/g/personal/lviegas_unicef_org/EXSCbDiDSptHiYtyiW4eqHsBg6kEow5wgghn0a8fcDI0yQ?e=7xS9Pz

 

Relatório de atividade - ​docx icon I3.4_2 Relatório de Atividade.docx - https://unicef-my.sharepoint.com/:w:/g/personal/lviegas_unicef_org/ERncZ0aO0QtItJd0zduMdh0BZdeXKec_2BUL8dwFBY9gdQ?e=dVTUeg 

 

Termo de Referência de Atividade - ​docx icon I3.4_1 Termo de Referência de atividade.docx - https://unicef-my.sharepoint.com/:w:/g/personal/lviegas_unicef_org/EQdIx8sPKtlCm-cW7e1QXMkBHs2JWZV0R-l1qq3xNoeDcw?e=ccenTI 

 

Relatório de Encerramento - ​docx icon I3.5_1 Relatório de Encerramento.docx - https://unicef-my.sharepoint.com/:w:/g/personal/lviegas_unicef_org/EXs6ii7AvhNErBbBi4OTrOMBv8Wkn0-dHFZ-IqdpMN8oPQ?e=18b2fC

**Comment by dlazaroni** [comment]
@Clivisonc Aqui também a gente queria um feedback seu de como prosseguir com o design (a partir da escolha de uma solução de desenvolvimento)

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
