### ISSUE TITLE
UI: Calendário - aplicação de Bryntum

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#317]
https://www.bryntum.com/store/scheduler/

**Comment by leonardodms-unicef** [comment]
https://xd.adobe.com/view/2ac17d7a-91d4-44de-87a1-cbeebde6a57d-7f92/

**Comment by leonardodms-unicef** [comment]
![317 - MAAp Calendário Mês.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/8d7ad167-8d97-4848-bdf1-76d4892745ea)

**Comment by leonardodms-unicef** [comment]
![317 - MAAp - Agenda.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/34c58492-3f4d-4459-8a03-7caad1c45576)

**Comment by leonardodms-unicef** [comment]
Em relatório: Set/22
