### ISSUE TITLE
DS: Grid system

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#5]

**Comment by leonardodms-unicef** [comment]
![Grid Large - 1140px.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/2bba352c-13bc-48e7-8c5c-647dae2f89f0)

**Comment by leonardodms-unicef** [comment]
Grid Medium
![Grid Medium - 960px.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/54883df5-9311-4f97-a625-6a374298b497)

**Comment by leonardodms-unicef** [comment]
Grid Small 
![Grid Small - 600px.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/cdab3027-dbd3-43c5-9064-50dd40b17c47)

**Comment by leonardodms-unicef** [comment]
Grid Extra Small
![Grid Extra Small - 320px.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/35ce3701-ab4d-4ef2-830e-c1f1ef54fc5e)
