### ISSUE TITLE
Wireframe RS3

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Design-System#63]
https://xd.adobe.com/view/a994ec12-c348-49a8-a786-b48d5496b2a2-fcc7/screen/fd64f8b6-ba4d-44a1-8782-6cb482c05f1f

**Comment by fialalucas** [comment]
wireframe torna-se desnecessário uma vez que adiantamos a task de UI

**Comment by dlazaroni** [comment]
https://xd.adobe.com/view/a994ec12-c348-49a8-a786-b48d5496b2a2-fcc7/
