### ISSUE TITLE
UI - Login

### ISSUE THREAD

**Issue by leonardodms-unicef** [UNICEF01/Design-System#78]
Desktop: https://xd.adobe.com/view/bb1d62fb-c304-45ae-a7a2-83365aa104f1-ee4e/

Mobile: https://xd.adobe.com/view/51abdccb-3e5f-48c3-9b9f-8e68e1753766-04f8/

**Comment by dlazaroni** [comment]
Ajustes:

- [ ] botões 50/50
- [ ] Negrito no nome (e-mail)
- [ ] Aumentar área da expansão do botão no texto dos termos
- [ ] Validação dos campos
- [ ] Remover navbar e trazer logo nas telas
- [ ] Trocar texto do "Enviei" em trocar senha
- [ ] Mix UI

**Comment by leonardodms-unicef** [comment]
![Primeiro Login - Cadastro – 1.png](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/bc9dfb92-f64b-417b-9b49-e5be911cf024)

**Comment by leonardodms-unicef** [comment]
![Senhas não conferem.jpg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/b0fe9de7-b5cb-4672-8d59-97de92f28fe7)

**Comment by leonardodms-unicef** [comment]
Em relatório: Abril/22
